# Generated by Django 4.0.8 on 2023-01-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_department_user_designation_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=50, null=True, verbose_name='Designation'),
        ),
    ]
