# Generated by Django 4.0.8 on 2023-01-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('ALL', 'All'), ('Operation', 'Operation'), ('Design & Business Development', 'Design & Business Development'), ('Merchandising', 'Merchandising')], max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Vice President', 'Vice President'), ('Business Head', 'Business Head'), ('Merchandising Manager', 'Merchandising Manager'), ('Merchandiser', 'Merchandiser'), ('Assistant Merchandiser', 'Assistant Merchandiser'), ('Trainee Merchandiser', 'Trainee Merchandiser'), ('Senior Merchandiser', 'Senior Merchandiser'), ('Assistant Merchandiser officer', 'Assistant Merchandiser officer')], max_length=50, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name of Employee'),
        ),
    ]
