# Generated by Django 4.0.8 on 2023-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entry Created At'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='Is Present'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_office_from',
            field=models.TimeField(null=True, verbose_name='Out Office From'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_office_to',
            field=models.TimeField(null=True, verbose_name='Out Office To'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Out Reason'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='regular_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Regular Hours'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Status'),
        ),
    ]
