# Generated by Django 4.0.8 on 2023-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_date_alter_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_office_from',
            field=models.TimeField(blank=True, verbose_name='Out Office From'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_office_to',
            field=models.TimeField(blank=True, verbose_name='Out Office To'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status'),
        ),
    ]
