# Generated by Django 4.0.8 on 2023-01-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_out_office_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='out_office_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Out Office From'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_office_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Out Office To'),
        ),
    ]
