# Generated by Django 4.0.8 on 2023-01-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/500_500.png', upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
